"""Builder functions for KL-001, KL-002, KL-003, KL-005, KL-006, KL-009, and KL-010 Kerala packages."""

from __future__ import annotations

from decimal import Decimal

from schemas.itineraries import (
    ItineraryCreate,
    ItineraryDayNested,
    ItineraryHighlightNested,
    ItineraryHotelNested,
    ItineraryInclusionNested,
)
from schemas.packages import PackageCreate, PackageHighlightNested
from services.package_image_specs import (
    KL_001_PEXELS_IMAGES,
    KL_002_PEXELS_IMAGES,
    KL_003_PEXELS_IMAGES,
    KL_005_PEXELS_IMAGES,
    KL_006_PEXELS_IMAGES,
    KL_009_PEXELS_IMAGES,
    KL_010_PEXELS_IMAGES,
)


def _standard_inclusions(extra_included: list[str] | None = None) -> list[ItineraryInclusionNested]:
    included_texts = [
        "Premium accommodation at handpicked Kerala resorts, heritage hotels, and luxury houseboats",
        "Daily lavish breakfasts and authentic Kerala multi-cuisine dinners (MAPAI plan)",
        "Private chauffeur-driven AC Innova Crysta for all transfers, hill stations, and sightseeing",
        "TRAGUIN 24/7 dedicated elite guest relationship manager assistance",
        "Personalized welcome kit with herbal tea, fresh fruits, mineral water, and houseboat transfers where applicable",
        "Driver allowances, tolls, parking, fuel, and applicable taxes",
    ]
    if extra_included:
        included_texts.extend(extra_included)
    excluded_texts = [
        "Airfare or train tickets to and from Cochin, Trivandrum, or Calicut gateway",
        "Monument entry tickets, national park fees, camera fees, and optional guide gratuities",
        "Optional activities such as speed-boating, elephant safaris, adventure sports, and spa therapies beyond included tier",
        "Personal expenses such as laundry, phone calls, alcoholic beverages, and tipping",
    ]
    items: list[ItineraryInclusionNested] = []
    sort_order = 1
    for text in included_texts:
        items.append(ItineraryInclusionNested(kind="included", text=text, sort_order=sort_order))
        sort_order += 1
    for text in excluded_texts:
        items.append(ItineraryInclusionNested(kind="excluded", text=text, sort_order=sort_order))
        sort_order += 1
    return items


def _senior_inclusions() -> list[ItineraryInclusionNested]:
    return [
        ItineraryInclusionNested(
            kind="included",
            text="Luxury hotel stays with step-free or easily accessible ground-floor rooms",
            sort_order=1,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="Daily breakfasts and custom low-spice gourmet dinners at all resorts",
            sort_order=2,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="Private 4-hour luxury Alleppey houseboat day cruise with custom mild-spice lunch",
            sort_order=3,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="Premium extra-comfortable luxury vehicle with captain seating for all transport",
            sort_order=4,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="Experienced personal chauffeur trained for senior guest care and flexible pacing",
            sort_order=5,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="Complimentary sunset cruise on Vembanad Lake and traditional welcome wellness drinks",
            sort_order=6,
        ),
        ItineraryInclusionNested(
            kind="included",
            text="All fuel costs, road tolls, parking fees, driver allowances, and TRAGUIN 24/7 remote concierge",
            sort_order=7,
        ),
        ItineraryInclusionNested(
            kind="excluded",
            text="Airfares, airport taxes, and train tickets",
            sort_order=8,
        ),
        ItineraryInclusionNested(
            kind="excluded",
            text="Entry tickets for monuments, historical palaces, or national parks",
            sort_order=9,
        ),
        ItineraryInclusionNested(
            kind="excluded",
            text="Personal expenses, optional intensive spa therapies, and travel or medical insurance",
            sort_order=10,
        ),
    ]


def build_kl_001(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 28
    package = PackageCreate(
        slug='kl-001-munnar-thekkady-alleppey-family',
        destination_id=destination_id,
        title='Premium Family — Munnar, Thekkady & Alleppey Houseboat',
        duration_label='05 Nights / 06 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Emerald Munnar tea plantations and mist-clad Western Ghats panoramas', sort_order=1),
            PackageHighlightNested(text='Exclusive spice plantation walk and Kathakali cultural evening in Thekkady', sort_order=2),
            PackageHighlightNested(text='Private ultra-luxury Alleppey houseboat cruise on Vembanad Lake with full board', sort_order=3),
            PackageHighlightNested(text='Fort Kochi heritage circuit — Chinese Fishing Nets, Jew Town & Dutch Palace', sort_order=4),
            PackageHighlightNested(text='Cheeyappara and Valara waterfall stops en route to Munnar', sort_order=5),
            PackageHighlightNested(text='Private Innova Crysta with TRAGUIN 24/7 family concierge throughout', sort_order=6),
        ],
        moods=['Family', 'Luxury', 'Nature'],
    )
    itinerary = ItineraryCreate(
        slug='kl-001-munnar-thekkady-alleppey-family-itinerary',
        destination_id=destination_id,
        title='Premium Family — Munnar, Thekkady & Alleppey Houseboat',
        duration_label='05 Nights / 06 Days',
        duration_days=6,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Paradise Found — A Premium Family Journey Through Kerala',
        overview="Immerse your family in the timeless magic of God's Own Country on TRAGUIN's definitive Kerala escape — from emerald tea slopes in Munnar and spice sanctuaries in Thekkady to a private Alleppey houseboat and Fort Kochi heritage. This premium curated journey weaves together breathtaking landscapes, handpicked resorts, and seamless private chauffeur comfort.",
        seo_title='KL-001 | Premium Family Kerala | TRAGUIN Munnar Thekkady Alleppey Tour',
        seo_description='Luxury 05 Nights / 06 Days Kerala family package (KL-001) covering Munnar tea valleys, Thekkady spice plantations, Alleppey houseboat, and Fort Kochi with premium stays and private transfers.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Munnar Tea Plantations & Waterfalls', sort_order=1),
            ItineraryHighlightNested(text='Thekkady Spice & Cultural Evening', sort_order=2),
            ItineraryHighlightNested(text='Alleppey Private Houseboat', sort_order=3),
            ItineraryHighlightNested(text='Fort Kochi Heritage Circuit', sort_order=4),
            ItineraryHighlightNested(text='Eravikulam National Park', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Cochin to Munnar — Ascent to the Emerald Hills',
                description='Your luxury Kerala holiday commences with a warm, personalized reception upon your arrival at Cochin International Airport or Railway Station. Your dedicated TRAGUIN professional chauffeur greets your family and assists with luggage before you step into your executive premium vehicle. Bid farewell to the urban coastal plains as you begin a scenic, winding ascent toward Munnar, the crown jewel of the Western Ghats. En route, pause at the spectacular Cheeyappara Waterfalls cascading down a seven-tiered rock face, and pass Valara Waterfalls embraced by dense forests before checking into your handpicked ultra-luxury resort overlooking cloud-kissed ridges.',
                activities=[
                    'Sightseeing Included: Cheeyappara Waterfalls, Valara Waterfalls, Panoramic Mountain Passes, Scenic Photo Points',
                    'Evening Experience: Leisurely walks around the premium resort estate or enjoying authentic Nilgiri tea amidst the evening mist',
                    'Overnight Stay: Munnar (Premium / Handpicked Luxury Resort)',
                    'Meals Included: Welcome Drink & Gourmet Buffet Dinner',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Munnar Sightseeing — Valleys of Velvet Tea',
                description='Awaken to a misty morning and indulge in an opulent breakfast before embarking on a comprehensive premium Munnar sightseeing tour. Visit the iconic Mattupetty Dam and reservoir, continue to Echo Point where voices resonate across the lake, wander through Kundala Lake, and tour the historic Tata Tea Museum. If conditions permit, visit Eravikulam National Park (Rajamalai), the sacred sanctuary of the endangered Nilgiri Tahr.',
                activities=[
                    'Sightseeing Included: Mattupetty Dam, Echo Point, Kundala Lake, Tea Museum, Photo Gardens, Eravikulam National Park',
                    'Optional Activities: Speed-boating at Mattupetty, paddle-boating on Kundala Lake, or shopping for rare exotic oils',
                    'Overnight Stay: Munnar (Premium / Handpicked Luxury Resort)',
                    'Meals Included: Sumptuous Breakfast & Elegant Dinner',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar to Thekkady — Heartland of Spices',
                description='Following a rich breakfast, check out of Munnar and chart a southerly path through spice-laden hills to Thekkady (Periyar). Arrive at your premium boutique resort and join an exclusive guided Spice Plantation Tour. As twilight falls, witness a breathtaking Kathakali performance or Kalaripayattu martial arts show at a cultural center.',
                activities=[
                    'Sightseeing Included: Spice Plantation Walk, Periyar Wilderness Outskirts, High-Range Viewpoints',
                    'Evening Experience: Live traditional Kathakali performance & vibrant Kalaripayattu martial arts show',
                    'Overnight Stay: Thekkady (Premium Wilderness Resort)',
                    'Meals Included: Breakfast & Multi-cuisine Buffet Dinner',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Thekkady to Alleppey — Ultimate Houseboat Cruise',
                description='Savor an early breakfast before departing for the pristine backwaters of Alleppey. Step aboard your private ultra-luxury TRAGUIN houseboat at noon. Glide onto Vembanad Lake as your onboard chef prepares authentic lunch featuring Karimeen Pollichathu. Watch the dramatic sunset before anchoring for a peaceful night under the stars.',
                activities=[
                    'Sightseeing Included: Vembanad Lake, Alleppey Backwater Canals, Remote Riverine Islands, Paddy Field Vistas',
                    'Optional Activities: Ayurvedic rejuvenation massage at a premium backwater spa during brief canal stops',
                    'Overnight Stay: Alleppey (Private Luxury Air-Conditioned Houseboat — Anchored)',
                    'Meals Included: Full Board — Traditional Lunch, High Tea, Dinner, and Breakfast cooked fresh onboard',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Alleppey to Cochin — Colonial Echoes of Fort Kochi',
                description='Enjoy breakfast on the houseboat deck as it cruises back to the mainland jetty. Disembark and travel to Cochin to explore Fort Kochi — the Chinese Fishing Nets, St. Francis Church, Jew Town, Paradesi Synagogue, and Mattancherry Dutch Palace.',
                activities=[
                    'Sightseeing Included: Fort Kochi Beach, Chinese Fishing Nets, St. Francis Church, Santa Cruz Basilica, Mattancherry Dutch Palace, Jew Town',
                    'Evening Experience: Leisurely café hopping in Fort Kochi or walking along Marine Drive promenade',
                    'Overnight Stay: Cochin (Premium / Ultra-Luxury Heritage Hotel)',
                    'Meals Included: Gourmet Breakfast & Farewell Dinner',
                ],
                sort_order=5,
            ),
            ItineraryDayNested(
                day_number=6,
                title='Departure from Cochin',
                description='Your exceptional TRAGUIN Kerala Package concludes today. Indulge in a final luxurious buffet breakfast and enjoy relaxed leisure time for last-minute shopping for tea leaves, organic spices, banana chips, or Kerala handloom garments before your private transfer to Cochin International Airport.',
                activities=[
                    'Sightseeing Included: Lulu Mall (optional) or local Cochin markets for souvenir shopping',
                    'Evening Experience: TRAGUIN farewell assistance and seamless airport check-in coordination',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Grand Institutional Breakfast',
                ],
                sort_order=6,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='The Leaf Munnar / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name="Chandy's Windy Woods / Similar",
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='The Panoramic Getaway / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Elephant Court / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Thekkady.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Greenwoods Resort / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Premium stay in Thekkady.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='The Niraamaya Retreats Cardamom Club / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Luxury stay in Thekkady.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='Spice Village Private Pool Villa / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Thekkady.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            ),
            ItineraryHotelNested(
                name='Premium AC Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Alleppey Houseboat.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=9,
            ),
            ItineraryHotelNested(
                name='Luxury Glass-Walled Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Premium stay in Alleppey Houseboat.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=10,
            ),
            ItineraryHotelNested(
                name='Ultra-Luxury Suite Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Luxury stay in Alleppey Houseboat.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=11,
            ),
            ItineraryHotelNested(
                name='TRAGUIN Signature Royal Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Alleppey Houseboat.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=12,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["05 nights premium accommodation across Munnar, Thekkady, Alleppey houseboat, and Cochin", "Guided spice plantation walk and cultural evening show entry tickets"]),
    )
    return package, itinerary, KL_001_PEXELS_IMAGES

def build_kl_002(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 29
    package = PackageCreate(
        slug='kl-002-cochin-munnar-kovalam-grand-family',
        destination_id=destination_id,
        title='Grand Family — Cochin, Munnar, Thekkady, Alleppey & Kovalam',
        duration_label='07 Nights / 08 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text="Grand hills-to-beach circuit from Fort Kochi to Kovalam's golden crescent cliffs", sort_order=1),
            PackageHighlightNested(text='Munnar tea valleys, Eravikulam Nilgiri Tahr sanctuary, and Mattupetty Dam', sort_order=2),
            PackageHighlightNested(text='Thekkady spice plantations with VIP Kathakali and Kalaripayattu evening', sort_order=3),
            PackageHighlightNested(text='Private Alleppey houseboat full-board cruise on Vembanad Lake', sort_order=4),
            PackageHighlightNested(text='Kovalam Lighthouse Beach and Trivandrum royal heritage exploration', sort_order=5),
            PackageHighlightNested(text='Private executive SUV with TRAGUIN 24/7 grand family concierge', sort_order=6),
        ],
        moods=['Family', 'Luxury', 'Beach'],
    )
    itinerary = ItineraryCreate(
        slug='kl-002-cochin-munnar-kovalam-grand-family-itinerary',
        destination_id=destination_id,
        title='Grand Family — Cochin, Munnar, Thekkady, Alleppey & Kovalam',
        duration_label='07 Nights / 08 Days',
        duration_days=8,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Grand Kerala Odyssey — Hills, Backwaters & Golden Beaches',
        overview="Embark on TRAGUIN's grand exploratory odyssey across God's Own Country — colonial Fort Kochi, cloud-swept Munnar tea valleys, Periyar spice forests, Alleppey houseboats, and majestic Kovalam beach sunrises with handpicked premium stays throughout.",
        seo_title='KL-002 | Grand Family Kerala | TRAGUIN Cochin Munnar Kovalam Tour',
        seo_description='Luxury 07 Nights / 08 Days grand Kerala family package (KL-002) covering Cochin, Munnar, Thekkady, Alleppey houseboat, and Kovalam with premium stays and private transfers.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Fort Kochi Heritage', sort_order=1),
            ItineraryHighlightNested(text='Munnar Tea & Eravikulam', sort_order=2),
            ItineraryHighlightNested(text='Thekkady Spice & Culture', sort_order=3),
            ItineraryHighlightNested(text='Alleppey Houseboat', sort_order=4),
            ItineraryHighlightNested(text='Kovalam Beach & Trivandrum', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Arrival in Cochin — Heritages of Fort Kochi',
                description='Your grand Kerala family tour begins with an elegant VIP welcome at Cochin International Airport. After checking into your luxury urban hotel, explore the multi-cultural colonial tapestry of Fort Kochi — Chinese Fishing Nets, Jew Town, Paradesi Synagogue, Mattancherry Dutch Palace, and St. Francis Church.',
                activities=[
                    'Sightseeing Included: Chinese Fishing Nets, Jew Town, Paradesi Synagogue, Mattancherry Palace, Fort Kochi Heritage Pathways',
                    'Evening Experience: Pleasant sunset ferry ride or walking down vibrant café-lined walkways of old Fort Kochi',
                    'Overnight Stay: Cochin (Premium Oceanfront Hotel)',
                    'Meals Included: Welcome Amenities & Grand Welcoming Dinner',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Cochin to Munnar — Cloud-Kissed Tea Horizons',
                description='Indulge in a magnificent breakfast before driving east toward Munnar through winding mountain passes. Pause at Cheeyappara and Valara Waterfalls, pass Adimali spice markets, and arrive at your ultra-luxury hill resort as evening mist rolls across the valley.',
                activities=[
                    'Sightseeing Included: Cheeyappara Waterfalls, Valara Waterfalls, Adimali Spice Markets, Neriamangalam Bridge',
                    'Evening Experience: Panoramic mountain gaps and mist settling over high-altitude valleys from your resort',
                    'Overnight Stay: Munnar (Handpicked Luxury Tea Resort)',
                    'Meals Included: Gourmet Breakfast & Fine-Dining Buffet Dinner',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar Hill Exploration — Velvet Greenery',
                description='TRAGUIN unlocks the finest natural treasures of Munnar — Mattupetty Dam with optional speed-boat, Echo Point, Kundala Arch Lake, Tata Tea Museum, and Eravikulam National Park for Nilgiri Tahr sightings.',
                activities=[
                    'Sightseeing Included: Mattupetty Dam, Echo Point, Kundala Arch Lake, Tea Museum, Eravikulam National Park',
                    'Optional Activities: Private speed-boating, estate tea shopping, or optional elephant interaction program',
                    'Overnight Stay: Munnar (Handpicked Luxury Tea Resort)',
                    'Meals Included: Resort Breakfast & Curated Theme Dinner',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Munnar to Thekkady — Spice Sanctum & Periyar',
                description='After breakfast, travel south to Thekkady through cardamom hills. Join a private Spice Plantation Tour with a resident botanist, then enjoy VIP seating for Kalaripayattu and Kathakali cultural performances.',
                activities=[
                    'Sightseeing Included: Periyar Forest Borders, Cardamom Estates, Local Handicraft Centers',
                    'Evening Experience: VIP seating for authentic Kathakali and Kalaripayattu cultural performances',
                    'Overnight Stay: Thekkady (Premium Wilderness Resort)',
                    'Meals Included: Full Breakfast & Authentic High-Range Dinner',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Thekkady to Alleppey — Floating Palaces',
                description='Depart the highlands for the emerald backwaters of Alleppey. Step aboard your exclusive ultra-luxury private houseboat at noon. Cruise Vembanad Lake past villages and paddy fields, watch the golden sunset, and anchor in a peaceful canal bay.',
                activities=[
                    'Sightseeing Included: Vembanad Lake, Alleppey Main Canals, Village Lagoons, Kuttanad Paddy Basins',
                    'Evening Experience: Relaxing on the open deck with fresh local snacks and hot tea as the sun dips below the horizon',
                    'Overnight Stay: Alleppey (Private Luxury Air-Conditioned Houseboat — Anchored)',
                    'Meals Included: Full Onboard Boarding — Breakfast, Lunch, High Tea & Dinner',
                ],
                sort_order=5,
            ),
            ItineraryDayNested(
                day_number=6,
                title='Alleppey to Kovalam — Crescent Cliffs',
                description='Wake to breakfast on deck as your houseboat returns to the jetty. Drive south along the coastal highway to Kovalam and check into your elite cliff-top resort overlooking the Arabian Sea. Relax on Lighthouse Beach.',
                activities=[
                    'Sightseeing Included: Lighthouse Beach, Hawah Beach, Coastal Highway Lookouts',
                    'Optional Activities: Climbing the Vizhinjam Lighthouse tower for sweeping coastal views',
                    'Overnight Stay: Kovalam (Premium Cliffside Beach Resort)',
                    'Meals Included: Fresh Houseboat Breakfast & Coastal Resort Dinner',
                ],
                sort_order=6,
            ),
            ItineraryDayNested(
                day_number=7,
                title='Kovalam Beach & Trivandrum Heritage',
                description='Enjoy a beachside breakfast before visiting Trivandrum — Sree Padmanabhaswamy Temple, Kuthira Malika Palace, and Napier Museum grounds. Return to Kovalam for Ayurvedic wellness or beach relaxation.',
                activities=[
                    'Sightseeing Included: Sree Padmanabhaswamy Temple (outer structures), Kuthira Malika Palace, Napier Museum grounds',
                    'Evening Experience: Private family celebration dinner arranged on the beach sands serenaded by crashing waves',
                    'Overnight Stay: Kovalam (Premium Cliffside Beach Resort)',
                    'Meals Included: Gourmet Breakfast & Farewell Seafood Dinner',
                ],
                sort_order=7,
            ),
            ItineraryDayNested(
                day_number=8,
                title='Kovalam to Trivandrum — Departure',
                description='Enjoy a relaxed breakfast overlooking the azure ocean. Complete check-out and your premium chauffeur transfers you to Trivandrum International Airport or Kochuveli Railway Station with cherished family memories.',
                activities=[
                    'Sightseeing Included: Final ocean views from Kovalam cliff and optional Vizhinjam lighthouse glimpse en route',
                    'Evening Experience: TRAGUIN farewell assistance at Trivandrum Airport or Kochuveli Railway Station',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Grand Institutional Breakfast',
                ],
                sort_order=8,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='Trident Cochin / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Cochin.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Crowne Plaza / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Premium stay in Cochin.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name='Grand Hyatt Bolgatty / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Luxury stay in Cochin.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='Brunton Boatyard / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Cochin.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='The Leaf Munnar / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name="Chandy's Windy Woods / Similar",
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='The Panoramic Getaway / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            ),
            ItineraryHotelNested(
                name='Elephant Court / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Thekkady.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=9,
            ),
            ItineraryHotelNested(
                name='Greenwoods Resort / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Premium stay in Thekkady.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=10,
            ),
            ItineraryHotelNested(
                name='Niraamaya Cardamom Club / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Luxury stay in Thekkady.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=11,
            ),
            ItineraryHotelNested(
                name='Spice Village Private Pool Villa / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Thekkady.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=12,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["07 nights premium accommodation across Cochin, Munnar, Thekkady, Alleppey houseboat, and Kovalam", "Complimentary candle-lit family dinner onboard private Alleppey houseboat"]),
    )
    return package, itinerary, KL_002_PEXELS_IMAGES

def build_kl_003(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 30
    package = PackageCreate(
        slug='kl-003-munnar-kochi-family',
        destination_id=destination_id,
        title='Munnar Kochi Family — Hill Station & Heritage Escape',
        duration_label='04 Nights / 05 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Three immersive nights in Munnar amid rolling tea estates and misty peaks', sort_order=1),
            PackageHighlightNested(text='Eravikulam National Park, Lock Heart Gap, and Pothamedu panoramic viewpoints', sort_order=2),
            PackageHighlightNested(text='Offbeat Blossom Hydel Park and exclusive family campfire evening', sort_order=3),
            PackageHighlightNested(text='Fort Kochi heritage — Chinese Fishing Nets, Jew Town & Dutch Palace', sort_order=4),
            PackageHighlightNested(text='Private Innova Crysta with TRAGUIN 24/7 family concierge', sort_order=5),
            PackageHighlightNested(text='Handpicked premium resorts in Munnar and heritage Kochi', sort_order=6),
        ],
        moods=['Family', 'Luxury', 'Nature'],
    )
    itinerary = ItineraryCreate(
        slug='kl-003-munnar-kochi-family-itinerary',
        destination_id=destination_id,
        title='Munnar Kochi Family — Hill Station & Heritage Escape',
        duration_label='04 Nights / 05 Days',
        duration_days=5,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Tea Hills & Colonial Charm — Munnar Meets Kochi',
        overview="Connect the historical coastal city of Kochi with the mist-laden peaks of Munnar on TRAGUIN's premium family getaway — three nights amid emerald tea estates, offbeat valley explorations, and a heritage Fort Kochi finale with seamless private luxury transit.",
        seo_title='KL-003 | Munnar Kochi Family | TRAGUIN Premium Kerala Tour',
        seo_description='Luxury 04 Nights / 05 Days Kerala family package (KL-003) covering Munnar tea hills, Lock Heart Gap, Eravikulam, and Fort Kochi heritage with premium stays.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Munnar Tea Estates & Waterfalls', sort_order=1),
            ItineraryHighlightNested(text='Lock Heart Gap & Pothamedu', sort_order=2),
            ItineraryHighlightNested(text='Eravikulam National Park', sort_order=3),
            ItineraryHighlightNested(text='Fort Kochi Heritage', sort_order=4),
            ItineraryHighlightNested(text='Family Campfire Evening', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Kochi to Munnar — Misty Hills Welcome',
                description='Arrive at Cochin International Airport where your TRAGUIN representative welcomes you. Commence a scenic drive toward Munnar through the Western Ghats, pausing at Cheeyappara and Valara Waterfalls and spice villages before checking into your handpicked luxury resort.',
                activities=[
                    'Sightseeing Included: Cheeyappara Waterfalls, Valara Waterfalls, Spice Plantation viewpoints',
                    'Evening Experience: Leisurely resort walk, high tea overlooking valleys, and traditional welcome dinner',
                    'Optional Activities: Traditional Ayurvedic rejuvenation massage at the resort spa',
                    'Overnight Stay: Munnar (Premium / Luxury Resort)',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Munnar Sightseeing — Tea Empire',
                description='Dedicated to comprehensive Munnar sightseeing — Eravikulam National Park (Rajamalai), Tata Tea Museum with tea tasting, Mattupetty Dam speed-boat cruise, Echo Point, and Kundala Lake surrounded by pine trees.',
                activities=[
                    'Sightseeing Included: Eravikulam National Park, Tata Tea Museum, Mattupetty Dam, Eco Point, Kundala Lake',
                    'Evening Experience: Strolling through old Munnar town market, sampling fresh local banana fritters',
                    'Optional Activities: Speed boating at Mattupetty; professional family photoshoot amidst tea gardens',
                    'Overnight Stay: Munnar (Premium / Luxury Resort)',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar Offbeat — Hidden Valleys',
                description='Explore Lock Heart Gap for sweeping valley views, Blossom Hydel Park with flower gardens, Pothamedu Viewpoint over tea and cardamom plantations, and interactive tea estate walks with local workers.',
                activities=[
                    'Sightseeing Included: Lock Heart Gap, Blossom Hydel Park, Pothamedu Viewpoint, Tea Estate interactive walks',
                    'Evening Experience: Exclusive family campfire with live acoustic music or traditional storytelling',
                    "Optional Activities: Jeep safari to Kolukkumalai — the world's highest tea estate for sunset views",
                    'Overnight Stay: Munnar (Premium / Luxury Resort)',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Munnar to Kochi — Colonial Heritage',
                description='Relish your final Munnar breakfast before descending to Kochi. Explore Chinese Fishing Nets, St. Francis Church, Jewish Synagogue in Jew Town, and Mattancherry Dutch Palace murals.',
                activities=[
                    'Sightseeing Included: Fort Kochi Chinese Fishing Nets, St. Francis Church, Jewish Synagogue, Dutch Palace',
                    'Evening Experience: Sunset harbor cruise observing shipping channels, followed by gourmet dinner',
                    'Optional Activities: Authentic evening Kathakali classical dance performance',
                    'Overnight Stay: Kochi (Premium Business / Heritage Luxury Hotel)',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Kochi Departure',
                description='Enjoy a leisurely breakfast and premium souvenir shopping for organic spices, tea blends, cashew nuts, and Kerala handloom attire before your seamless transfer to Cochin International Airport.',
                activities=[
                    'Sightseeing Included: Jew Town shopping walk, Lulu Mall visit (optional based on flight timing)',
                    'Evening Experience: TRAGUIN farewell assistance and seamless airport check-in coordination',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Breakfast',
                ],
                sort_order=5,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='The Leaf Munnar / Similar',
                location='Munnar (3N)',
                nights_label='03 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel / Similar',
                location='Munnar (3N)',
                nights_label='03 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name="Chandy's Windy Woods / Similar",
                location='Munnar (3N)',
                nights_label='03 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='Spice Tree / Windermere Estate / Similar',
                location='Munnar (3N)',
                nights_label='03 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Trident Cochin / Similar',
                location='Kochi (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Kochi.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Brunton Boatyard / Similar',
                location='Kochi (1N)',
                nights_label='01 Night',
                description='Premium stay in Kochi.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='Cochin Marriott / Taj Malabar / Similar',
                location='Kochi (1N)',
                nights_label='01 Night',
                description='Luxury stay in Kochi.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='Taj Malabar Heritage / Grand Hyatt Presidential / Similar',
                location='Kochi (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Kochi.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["04 nights premium accommodation — 03 nights Munnar and 01 night Kochi", "Private high-tea at an exclusive scenic Munnar viewpoint"]),
    )
    return package, itinerary, KL_003_PEXELS_IMAGES

def build_kl_005(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 31
    package = PackageCreate(
        slug='kl-005-romantic-honeymoon-munnar-alleppey',
        destination_id=destination_id,
        title='Romantic Honeymoon — Munnar & Alleppey Houseboat',
        duration_label='04 Nights / 05 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Intimate Munnar hill retreat with TRAGUIN Signature candlelit dinner in a private pavilion', sort_order=1),
            PackageHighlightNested(text='Eravikulam National Park, Echo Point, and endless tea estate couple photography', sort_order=2),
            PackageHighlightNested(text='Private luxury Alleppey houseboat full-board cruise on Vembanad Lake', sort_order=3),
            PackageHighlightNested(text='Fort Kochi heritage walk — Chinese Fishing Nets, Jew Town & Dutch Palace', sort_order=4),
            PackageHighlightNested(text='Honeymoon welcome amenities — floral bed decoration and sparkling juice', sort_order=5),
            PackageHighlightNested(text='Private chauffeur-driven luxury vehicle with TRAGUIN 24/7 romance concierge', sort_order=6),
        ],
        moods=['Romantic', 'Luxury', 'Nature'],
    )
    itinerary = ItineraryCreate(
        slug='kl-005-romantic-honeymoon-munnar-alleppey-itinerary',
        destination_id=destination_id,
        title='Romantic Honeymoon — Munnar & Alleppey Houseboat',
        duration_label='04 Nights / 05 Days',
        duration_days=5,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline="Love in God's Own Country — Munnar Hills & Alleppey Backwaters",
        overview='A captivating Kerala honeymoon weaving mist-kissed Munnar emerald hills with romantic Alleppey backwaters — private premium stays, TRAGUIN Signature candlelit dining, and seamless luxury transfers curated exclusively for newlyweds.',
        seo_title='KL-005 | Romantic Honeymoon Kerala | TRAGUIN Munnar Alleppey Tour',
        seo_description='Luxury 04 Nights / 05 Days Kerala honeymoon package (KL-005) covering Munnar tea estates, private Alleppey houseboat, and Fort Kochi with premium romance experiences.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Munnar Romantic Tea Estates', sort_order=1),
            ItineraryHighlightNested(text='TRAGUIN Candlelit Dinner', sort_order=2),
            ItineraryHighlightNested(text='Private Alleppey Houseboat', sort_order=3),
            ItineraryHighlightNested(text='Fort Kochi Heritage', sort_order=4),
            ItineraryHighlightNested(text='Vembanad Sunset Cruise', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Cochin to Munnar — Welcome to the Emerald Hills',
                description='Upon arrival at Cochin International Airport, your luxury transport sweeps you toward Munnar through the Western Ghats. Stop at Cheeyappara and Valara waterfalls before arriving at your handpicked luxury resort with special honeymoon welcome amenities.',
                activities=[
                    'Sightseeing Included: Cheeyappara & Valara Waterfalls, Karadipara View Point, Scenic Mountain Highway Drive',
                    'Evening Experience: Private stroll through resort organic gardens followed by tailored multi-course dinner',
                    'Optional Activities: Evening traditional Kathakali or Kalaripayattu cultural performance',
                    'Overnight Stay: Munnar (Handpicked Premium Resort)',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Munnar Sightseeing — Mist, Mountains & Romance',
                description='Explore Eravikulam National Park hand-in-hand, visit Mattupetty Dam and Kundala Lake, share a whisper at Echo Point, and capture photographs amidst endless green Tata Tea Estates.',
                activities=[
                    'Sightseeing Included: Eravikulam National Park, Mattupetty Dam, Echo Point, Kundala Lake, Photo Point, Tea Museum',
                    'Evening Experience: TRAGUIN Signature romantic candlelit dinner arranged in a private pavilion',
                    "Optional Activities: Guided premium tea tasting session or private couple's plantation trek",
                    'Overnight Stay: Munnar (Handpicked Premium Resort)',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar to Alleppey — Cruise of Eternal Togetherness',
                description='Descend toward Alleppey and step aboard an exclusive private luxury houseboat. Glide through palm-fringed canals and paddy fields as your onboard chef prepares hyper-local delicacies. Watch the golden sunset over the backwaters.',
                activities=[
                    'Sightseeing Included: Vembanad Lake cruising, Alleppey narrow backwater canals, local rural life viewing',
                    'Evening Experience: Relaxing on the open deck under stars; overnight anchoring in the serene heart of the lake',
                    'Optional Activities: Traditional village canoe ride through ultra-narrow canals for authentic photography',
                    'Overnight Stay: Alleppey (Premium Private Luxury Houseboat — Air Conditioned)',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Alleppey to Cochin — Heritage & Coastal Luxury',
                description='Witness sunrise over the water as your houseboat glides back to the jetty. Discover Fort Cochin and Mattancherry — Chinese Fishing Nets, Paradesi Synagogue, and Mattancherry Dutch Palace before gourmet seafood dining.',
                activities=[
                    'Sightseeing Included: Fort Cochin, Chinese Fishing Nets, St. Francis Church, Mattancherry Palace, Jew Town',
                    'Evening Experience: Gourmet dining at a renowned seafood specialty restaurant in Cochin',
                    'Optional Activities: Premium harbor sunset cruise or high-tea at a historical heritage waterfront hotel',
                    'Overnight Stay: Cochin (Premium Luxury Hotel)',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Departure from Cochin',
                description='Savor your final coastal breakfast. Enjoy relaxed leisure or last-minute artisan souvenir shopping before your private transfer to Cochin International Airport.',
                activities=[
                    'Sightseeing Included: Airport transit route viewing, optional brief stopovers for local spice purchases',
                    'Evening Experience: TRAGUIN farewell assistance and seamless airport check-in coordination',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Breakfast',
                ],
                sort_order=5,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='The Leaf Munnar / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel & Spa / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name="Chandy's Windy Woods / Similar",
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='Spice Tree Munnar / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Premium AC Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Alleppey Houseboat.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Luxury Glass Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Premium stay in Alleppey Houseboat.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='Super Luxury Cruise Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Luxury stay in Alleppey Houseboat.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='TRAGUIN Signature Elite Houseboat / Similar',
                location='Alleppey Houseboat (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Alleppey Houseboat.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            ),
            ItineraryHotelNested(
                name='Trident Cochin / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Cochin.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=9,
            ),
            ItineraryHotelNested(
                name='Brunton Boatyard / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Premium stay in Cochin.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=10,
            ),
            ItineraryHotelNested(
                name='Grand Hyatt Bolgatty / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Luxury stay in Cochin.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=11,
            ),
            ItineraryHotelNested(
                name='The Leela / Cochin Elite / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Cochin.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=12,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["04 nights premium accommodation across Munnar, Alleppey houseboat, and Cochin", "Honeymoon cake, floral bed decoration, and one exclusive candlelight dinner in Munnar"]),
    )
    return package, itinerary, KL_005_PEXELS_IMAGES

def build_kl_006(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 32
    package = PackageCreate(
        slug='kl-006-honeymoon-romance-munnar-kovalam',
        destination_id=destination_id,
        title='Honeymoon Romance — Munnar, Thekkady, Alleppey & Kovalam',
        duration_label='05 Nights / 06 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Complete honeymoon circuit — Munnar tea romance, Thekkady spice wilderness, Alleppey houseboat, Kovalam cliffs', sort_order=1),
            PackageHighlightNested(text='Periyar Lake boating and VIP Kathakali cultural evening in Thekkady', sort_order=2),
            PackageHighlightNested(text='Private Kettuvallam houseboat with Karimeen Pollichathu and candlelit deck dinner', sort_order=3),
            PackageHighlightNested(text='Kovalam Lighthouse Beach sundowners and Ayurvedic spa options', sort_order=4),
            PackageHighlightNested(text='Honeymoon cake, floral bed decoration, and TRAGUIN candlelit valley dining', sort_order=5),
            PackageHighlightNested(text='Private premium vehicle with TRAGUIN 24/7 honeymoon concierge', sort_order=6),
        ],
        moods=['Romantic', 'Luxury', 'Beach'],
    )
    itinerary = ItineraryCreate(
        slug='kl-006-honeymoon-romance-munnar-kovalam-itinerary',
        destination_id=destination_id,
        title='Honeymoon Romance — Munnar, Thekkady, Alleppey & Kovalam',
        duration_label='05 Nights / 06 Days',
        duration_days=6,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Romance Across Kerala — Hills, Spices, Backwaters & Sea',
        overview="TRAGUIN's ultimate Kerala honeymoon weaves aromatic Munnar tea plantations, Thekkady wildlife mysteries, an exclusive Alleppey backwater cruise, and dramatic Kovalam clifftop coastlines — secluded privacy, candlelit dinners, and premium handpicked stays throughout.",
        seo_title='KL-006 | Honeymoon Romance Kerala | TRAGUIN Munnar Thekkady Kovalam Tour',
        seo_description='Luxury 05 Nights / 06 Days Kerala honeymoon package (KL-006) covering Munnar, Thekkady, Alleppey houseboat, and Kovalam with premium romance experiences.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Munnar Tea Romance', sort_order=1),
            ItineraryHighlightNested(text='Thekkady Periyar & Spice', sort_order=2),
            ItineraryHighlightNested(text='Alleppey Private Houseboat', sort_order=3),
            ItineraryHighlightNested(text='Kovalam Cliff Beach', sort_order=4),
            ItineraryHighlightNested(text='TRAGUIN Candlelit Dining', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Cochin Arrival to Munnar — Misty Hills Welcome',
                description='Arrive at Cochin where a TRAGUIN representative welcomes you with traditional garlands. Drive toward Munnar through Cheeyappara and Valara Waterfalls, check into your ultra-luxury resort, and unwind on your private balcony overlooking the clouds.',
                activities=[
                    'Sightseeing Included: Cheeyappara & Valara Waterfalls, Adimali Spice Markets, Scenic Mountain Drive',
                    'Evening Experience: Private candlelight dining orientation overlooking the mist-clad valley',
                    'Optional Activities: Traditional Kerala Ayurvedic welcome massage at the resort',
                    'Overnight Stay: Munnar (Premium Resort)',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Munnar Sightseeing — Tea Estate Trails',
                description='Visit Mattupetty Dam and Lake, Echo Point, Kundala Lake, private Tata Tea Plantation walk with tea tasting, and Eravikulam National Park — home of the Nilgiri Tahr.',
                activities=[
                    'Sightseeing Included: Eravikulam National Park, Mattupetty Dam, Echo Point, Kundala Lake, Tea Museum',
                    'Evening Experience: Leisurely walk through colonial-era Munnar town market for rare spices and handmade chocolates',
                    "Optional Activities: Speed boating at Mattupetty; private couples' photo session in tea gardens",
                    'Overnight Stay: Munnar (Premium Resort)',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar to Thekkady — Wildlife & Spice Odyssey',
                description='Drive through the Western Ghats to Thekkady. Enjoy an immersive spice plantation tour, tranquil Periyar Lake boating in the Tiger Reserve, and VIP Kathakali and Kalaripayattu cultural shows.',
                activities=[
                    'Sightseeing Included: Periyar Lake Boating, Spice Plantation Tour, Periyar Tiger Reserve',
                    'Evening Experience: VIP seating at local theatre for Kalaripayattu and Kathakali cultural shows',
                    'Optional Activities: Elephant interaction program or guided jungle night patrol walk',
                    'Overnight Stay: Thekkady (Luxury Spice Resort)',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Thekkady to Alleppey — Private Backwater Cruise',
                description='Step onto your exclusive private luxury Kettuvallam houseboat. Glide along Vembanad Lake and palm-fringed canals with Karimeen Pollichathu lunch onboard — the centerpiece of your Kerala honeymoon.',
                activities=[
                    'Sightseeing Included: Vembanad Lake, Alleppey Backwater Canals, Paddy Field Views',
                    'Evening Experience: Breathtaking sunset from the houseboat deck followed by romantic candlelit dinner',
                    'Optional Activities: Traditional village canoe cruise to explore narrow water alleys',
                    'Overnight Stay: Alleppey (Private Luxury Houseboat — Anchored in Serene Backwaters)',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Alleppey to Kovalam — Sun-Kissed Cliffs',
                description='Cruise back to the jetty after breakfast and drive south to Kovalam. Check into a spectacular clifftop resort and relax on Lighthouse Beach, Hawa Beach, or Samudra Beach.',
                activities=[
                    'Sightseeing Included: Kovalam Beach Circuit, Vizhinjam Lighthouse, Marine Aquarium',
                    'Evening Experience: Private seaside sundowner cocktail session followed by gourmet seafood dinner',
                    'Overnight Stay: Kovalam (Luxury Beach Resort)',
                    'Meals Included: Breakfast & Dinner',
                ],
                sort_order=5,
            ),
            ItineraryDayNested(
                day_number=6,
                title='Kovalam to Trivandrum — Departure',
                description='Conclude with a relaxed ocean breakfast. Brief Trivandrum city tour of Sree Padmanabhaswamy Temple before transfer to Trivandrum International Airport or railway station.',
                activities=[
                    'Sightseeing Included: Sree Padmanabhaswamy Temple (outer view), Napier Museum',
                    'Evening Experience: TRAGUIN farewell assistance at Trivandrum Airport or railway station',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Premium Buffet Breakfast',
                ],
                sort_order=6,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='The Fog Munnar / Leaf Resort / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel / Amber Dale / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name="Fragrant Nature / Chandy's Windy Woods / Similar",
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='Elixir Hills / Windermere Estate / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Greenwoods Resort / Poetree / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Thekkady.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Elephant Court / Spice Village / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Premium stay in Thekkady.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='Cardamom County / Niraamaya Wilderness / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Luxury stay in Thekkady.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='Spice Village CGH Earth Private Villa / Similar',
                location='Thekkady (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Thekkady.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            ),
            ItineraryHotelNested(
                name='Premium Private Houseboat / Similar',
                location='Alleppey (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Alleppey.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=9,
            ),
            ItineraryHotelNested(
                name='Luxury Private Houseboat / Similar',
                location='Alleppey (1N)',
                nights_label='01 Night',
                description='Premium stay in Alleppey.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=10,
            ),
            ItineraryHotelNested(
                name='Ultra Luxury Houseboat Suite / Similar',
                location='Alleppey (1N)',
                nights_label='01 Night',
                description='Luxury stay in Alleppey.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=11,
            ),
            ItineraryHotelNested(
                name='Xandari Riverscapes Houseboat / Similar',
                location='Alleppey (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Alleppey.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=12,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["05 nights premium accommodation across Munnar, Thekkady, Alleppey houseboat, and Kovalam", "Guided spice plantation walk, tea estate trail, and honeymoon welcome amenities"]),
    )
    return package, itinerary, KL_006_PEXELS_IMAGES

def build_kl_009(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 33
    package = PackageCreate(
        slug='kl-009-senior-citizen-kumarakom-relaxed',
        destination_id=destination_id,
        title='Senior Citizen Relaxed — Munnar, Kumarakom & Alleppey',
        duration_label='05 Nights / 06 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Gracefully paced Relax Kerala passage designed for senior citizens and relaxed families', sort_order=1),
            PackageHighlightNested(text='Step-free ground-floor rooms, captain-seat luxury van, and patient chauffeur care', sort_order=2),
            PackageHighlightNested(text='Gentle Munnar tea garden panoramas without steep trekking requirements', sort_order=3),
            PackageHighlightNested(text='Two serene nights at Kumarakom lakefront resort with bird sanctuary and sunset cruise', sort_order=4),
            PackageHighlightNested(text='4-hour premium Alleppey houseboat day cruise with mild-spice onboard lunch', sort_order=5),
            PackageHighlightNested(text='TRAGUIN 24/7 remote concierge with daily senior guest comfort check-ins', sort_order=6),
        ],
        moods=['Family', 'Luxury', 'Wellness'],
    )
    itinerary = ItineraryCreate(
        slug='kl-009-senior-citizen-kumarakom-relaxed-itinerary',
        destination_id=destination_id,
        title='Senior Citizen Relaxed — Munnar, Kumarakom & Alleppey',
        duration_label='05 Nights / 06 Days',
        duration_days=6,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Relax Kerala — Graceful Comfort for Senior Travellers',
        overview="A gracefully paced ultra-comfortable journey through God's Own Country purposefully designed for senior citizens — slow tea garden walks in Munnar, therapeutic Kumarakom lakefront serenity, a premium Alleppey day cruise, and accessible Fort Kochi heritage with zero fatigue and maximum luxury.",
        seo_title='KL-009 | Senior Citizen Kerala | TRAGUIN Relax Kerala Passage',
        seo_description='Luxury 05 Nights / 06 Days senior-friendly Kerala package (KL-009) covering Munnar, Kumarakom, Alleppey day cruise, and Cochin with accessible premium stays.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Accessible Munnar Tea Views', sort_order=1),
            ItineraryHighlightNested(text='Kumarakom Lake Serenity', sort_order=2),
            ItineraryHighlightNested(text='Alleppey Day Houseboat Cruise', sort_order=3),
            ItineraryHighlightNested(text='Fort Kochi Heritage', sort_order=4),
            ItineraryHighlightNested(text='Bird Sanctuary & Wellness', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Cochin to Munnar — Smooth Ascent to Mist-Kissed Hills',
                description='Your journey begins with a smooth arrival at Cochin International Airport where a TRAGUIN guest relations officer welcomes you with fresh flower garlands. Travel in a spacious premium vehicle with wide doors and captain-style seats toward Munnar, pausing to admire Cheeyappara Waterfalls from roadside viewpoints.',
                activities=[
                    'Sightseeing Included: Roadside views of Cheeyappara & Valara Falls, Western Ghats Scenic Drive',
                    'Evening Experience: Relaxed evening at the resort garden terrace with light classical flute music',
                    'Overnight Stay: Munnar (Handpicked Senior-Friendly Luxury Resort)',
                    'Meals Included: Custom Gourmet Dinner (Mild Spices)',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Munnar Hills — Tea Garden Panoramas',
                description='Gentle Munnar sightseeing avoiding steep paths — Mattupetty Dam lakeside promenade, accessible Tea Museum, Echo Point flat trail, and curated walk through an organic spice and tea nursery.',
                activities=[
                    'Sightseeing Included: Mattupetty Dam viewpoint, Echo Point flat trail, Tea Museum, Lockhart Garden Gallery',
                    'Evening Experience: Private interactive session with a local tea master demonstrating artisanal brewing methods',
                    'Optional Activities: Mild Ayurvedic foot reflexology treatment at the resort wellness center',
                    'Overnight Stay: Munnar (Handpicked Senior-Friendly Luxury Resort)',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Munnar to Kumarakom — Tranquil Lakeside',
                description='After a leisurely breakfast, your chauffeur guides the luxury vehicle down smooth slopes to Kumarakom on Vembanad Lake. Check into your waterfront resort and enjoy a relaxing sunset boat cruise with traditional light snacks.',
                activities=[
                    'Sightseeing Included: Scenic downhill drive, Kumarakom Lake Vistas',
                    'Evening Experience: Relaxing sunset boat cruise directly from the resort jetty with traditional light snacks onboard',
                    'Optional Activities: Gentle authentic Ayurvedic full-body rejuvenation massage focusing on joint comfort',
                    'Overnight Stay: Kumarakom (Premium Waterfront Luxury Resort)',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='Kumarakom — Day of Absolute Rest',
                description='A completely relaxed day — optional gentle chair-yoga, long breakfast with fresh tropical fruits, electric golf-cart resort tour, and Kumarakom Bird Sanctuary on accessible flat paths.',
                activities=[
                    'Sightseeing Included: Kumarakom Bird Sanctuary entry (accessible flat paths or golf-cart views)',
                    'Evening Experience: Classic Kathakali dance performance from comfortable reserved front-row seats',
                    'Optional Activities: Pottery making, traditional indoor games, or consultation with a wellness expert',
                    'Overnight Stay: Kumarakom (Premium Waterfront Luxury Resort)',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Alleppey Day Cruise to Cochin — Backwater & Heritage',
                description='Drive to Alleppey for an exclusive ultra-luxury private houseboat day cruise with flat decks and wide seating. Enjoy a mild-spice lunch onboard, then continue to your heritage hotel in Fort Cochin for a relaxed final evening at Chinese Fishing Nets.',
                activities=[
                    'Sightseeing Included: 4-Hour Exclusive Backwater Cruise, Alleppey Lagoons, Fort Cochin Heritage Drive',
                    'Evening Experience: Relaxed stroll to see historic Chinese Fishing Nets at sunset from the paved beach promenade',
                    'Overnight Stay: Cochin (Premium Heritage Luxury Hotel)',
                    'Meals Included: Breakfast, Traditional Houseboat Lunch & Farewell Dinner',
                ],
                sort_order=5,
            ),
            ItineraryDayNested(
                day_number=6,
                title='Cochin Departure',
                description='Enjoy a relaxed breakfast at your heritage hotel. Stop at a luxury boutique center for handwoven shawls, tea blends, or aromatic spices before a comfortable assisted transfer to Cochin International Airport.',
                activities=[
                    'Sightseeing Included: Flexible morning drive through Fort Cochin or localized boutique shopping',
                    'Evening Experience: TRAGUIN assisted luggage handling and seamless airport check-in coordination',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Premium Breakfast',
                ],
                sort_order=6,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='The Fog Munnar / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Munnar.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='Blanket Hotel & Spa / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Premium stay in Munnar.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name="Chandy's Windy Woods / Similar",
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Munnar.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='The Panoramic Getaway / Similar',
                location='Munnar (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Munnar.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Abad Whispering Palms / Similar',
                location='Kumarakom (2N)',
                nights_label='02 Nights',
                description='Deluxe stay in Kumarakom.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Kumarakom Lake Resort / Similar',
                location='Kumarakom (2N)',
                nights_label='02 Nights',
                description='Premium stay in Kumarakom.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='The Zuri Kumarakom / Similar',
                location='Kumarakom (2N)',
                nights_label='02 Nights',
                description='Luxury stay in Kumarakom.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='Niraamaya Retreats Backwaters & Beyond / Similar',
                location='Kumarakom (2N)',
                nights_label='02 Nights',
                description='Ultra Luxury stay in Kumarakom.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            ),
            ItineraryHotelNested(
                name='Trident Cochin / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Deluxe stay in Cochin.',
                stars=4,
                category_label='Deluxe',
                room_type='Executive Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=9,
            ),
            ItineraryHotelNested(
                name='Fragrant Nature Cochin / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Premium stay in Cochin.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=10,
            ),
            ItineraryHotelNested(
                name='Brunton Boatyard / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Luxury stay in Cochin.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Room / Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=11,
            ),
            ItineraryHotelNested(
                name='The Malabar House / Similar',
                location='Cochin (1N)',
                nights_label='01 Night',
                description='Ultra Luxury stay in Cochin.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Luxury Suite / Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=12,
            )
        ],
        inclusions=_senior_inclusions(),
    )
    return package, itinerary, KL_009_PEXELS_IMAGES

def build_kl_010(destination_id: str) -> tuple[PackageCreate, ItineraryCreate, list]:
    featured_sort_order = 34
    package = PackageCreate(
        slug='kl-010-wayanad-adventure-escape',
        destination_id=destination_id,
        title='Wayanad Adventure — Chembra, Edakkal & Kuruva Island',
        duration_label='04 Nights / 05 Days',
        price=0,
        rating=Decimal("4.9"),
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            PackageHighlightNested(text='Chembra Peak trek to the iconic heart-shaped Hridayasaras lake', sort_order=1),
            PackageHighlightNested(text='Edakkal Caves Neolithic petroglyphs and Muthanga Wildlife 4x4 jeep safari', sort_order=2),
            PackageHighlightNested(text='900 Kandi glass bridge canopy walk and Kuruva Island bamboo rafting', sort_order=3),
            PackageHighlightNested(text="Banasura Sagar Dam speed boating — India's largest earth dam", sort_order=4),
            PackageHighlightNested(text='Specialized adventure guides, skip-the-line trek passes, and campfire evenings', sort_order=5),
            PackageHighlightNested(text='Private Innova Crysta SUV with TRAGUIN 24/7 adventure concierge', sort_order=6),
        ],
        moods=['Adventure', 'Nature', 'Luxury'],
    )
    itinerary = ItineraryCreate(
        slug='kl-010-wayanad-adventure-escape-itinerary',
        destination_id=destination_id,
        title='Wayanad Adventure — Chembra, Edakkal & Kuruva Island',
        duration_label='04 Nights / 05 Days',
        duration_days=5,
        starting_price=0,
        price_note="On Request (Premium Curated)",
        rating=Decimal("4.9"),
        review_count=0,
        tagline='Wild Wayanad — Adventure Meets Premium Eco-Luxury',
        overview="TRAGUIN's Wayanad Adventure Escape blends high-octane thrill with pristine nature — Chembra Peak trekking, prehistoric Edakkal Caves, Muthanga jeep safari, 900 Kandi glass bridge, and Kuruva bamboo rafting wrapped in handpicked premium eco-resort comfort.",
        seo_title='KL-010 | Wayanad Adventure Kerala | TRAGUIN Chembra Edakkal Tour',
        seo_description='Luxury 04 Nights / 05 Days Wayanad adventure package (KL-010) covering Chembra Peak, Edakkal Caves, Banasura Dam, 900 Kandi, and Kuruva Island with premium eco-resorts.',
        is_featured=True,
        featured_sort_order=featured_sort_order,
        is_published=True,
        highlights=[
            ItineraryHighlightNested(text='Chembra Peak & Heart Lake', sort_order=1),
            ItineraryHighlightNested(text='Edakkal Caves Petroglyphs', sort_order=2),
            ItineraryHighlightNested(text='Muthanga Jeep Safari', sort_order=3),
            ItineraryHighlightNested(text='900 Kandi Glass Bridge', sort_order=4),
            ItineraryHighlightNested(text='Kuruva Bamboo Rafting', sort_order=5),
        ],
        days=[
            ItineraryDayNested(
                day_number=1,
                title='Calicut to Wayanad — Gateway to Misty Hills',
                description='Arrive at Calicut Airport or Railway Station where your TRAGUIN chauffeured vehicle welcomes you. Wind upward through the legendary Lakkidi Ghat Pass with 9 hairpin curves, pause at Lakkidi View Point, and check into your luxury eco-resort in Vythiri nestled in dense rainforests.',
                activities=[
                    'Sightseeing Included: Lakkidi Ghat Pass, Lakkidi View Point, Ficus Tree (Chain Tree) Legend Site',
                    'Evening Experience: Private indoor candle-lit ambient tea tasting session',
                    'Optional Activities: Premium Ayurvedic spa rejuvenation therapy at the resort',
                    'Overnight Stay: Vythiri / Kalpetta (Handpicked Luxury Eco-Resort)',
                ],
                sort_order=1,
            ),
            ItineraryDayNested(
                day_number=2,
                title='Chembra Peak & Banasura Dam — Heart-Shaped Lake',
                description="Rise early for an exhilarating Chembra Peak trek with a certified local tracker through tea estates and shola forests to the heart-shaped Hridayasaras lake. After lunch, visit Banasura Sagar Dam — India's largest earth dam — with speed boating across the reservoir.",
                activities=[
                    'Sightseeing Included: Chembra Peak Trekking, Heart-Shaped Lake, Banasura Sagar Dam, Karlad Lake',
                    'Evening Experience: Zipline over water bodies catching golden sunset views',
                    'Optional Activities: High-speed zip-lining and rock climbing at Karlad Lake adventure hub',
                    'Overnight Stay: Vythiri / Kalpetta (Handpicked Luxury Eco-Resort)',
                ],
                sort_order=2,
            ),
            ItineraryDayNested(
                day_number=3,
                title='Edakkal Caves & Muthanga Jeep Safari',
                description='Trek to Edakkal Caves on Ambukuthi Mala to see Neolithic petroglyphs dating back over 8,000 years. Explore Sulthan Bathery heritage, then embark on an exclusive 4x4 open jeep safari into Muthanga Wildlife Sanctuary.',
                activities=[
                    'Sightseeing Included: Edakkal Caves, Sulthan Bathery Jain Temple, Muthanga Wildlife Sanctuary Zone',
                    'Evening Experience: Traditional live multi-course dinner accompanied by a light campfire setting',
                    'Optional Activities: Tribal archery interaction and local bamboo crafts workshop',
                    'Overnight Stay: Sulthan Bathery (Premium Boutique Resort)',
                ],
                sort_order=3,
            ),
            ItineraryDayNested(
                day_number=4,
                title='900 Kandi & Kuruva Island — Canopy Walk & Bamboo Rafting',
                description='Board a rugged off-road vehicle to 900 Kandi eco-park and walk the thrilling glass bridge suspended above the jungle canopy. Continue to Kuruvadweep for traditional hand-woven bamboo rafting on the Kabini River, with optional Soochipara Waterfalls.',
                activities=[
                    'Sightseeing Included: 900 Kandi Eco-Park, Glass Bridge Walkway, Kuruvadweep Bamboo Rafting, Soochipara Waterfalls',
                    'Evening Experience: Bespoke interactive session with a professional naturalist on Western Ghats biodiversity',
                    'Optional Activities: River trekking and wild stream bathing under expert safety supervision',
                    'Overnight Stay: Sulthan Bathery (Premium Boutique Resort)',
                ],
                sort_order=4,
            ),
            ItineraryDayNested(
                day_number=5,
                title='Wayanad to Calicut — Departure',
                description='Relish an elite breakfast before check-out. Cruise back toward Calicut with stops at Pookode Lake and local spice plantations for organic cardamom, vanilla pods, chocolates, and Malabar tea leaves.',
                activities=[
                    'Sightseeing Included: Pookode Lake (en-route boating), Local Spice and Tea Plantations',
                    'Evening Experience: TRAGUIN farewell assistance at Calicut Airport or Railway Station',
                    'Overnight Stay: Not Applicable (Departure Day)',
                    'Meals Included: Premium Breakfast',
                ],
                sort_order=5,
            )
        ],
        hotels=[
            ItineraryHotelNested(
                name='Vythiri Village Resort / Similar',
                location='Vythiri / Kalpetta (2N)',
                nights_label='02 Nights',
                description='Deluxe hill-view eco-resort in Wayanad rainforest.',
                stars=4,
                category_label='Deluxe',
                room_type='Deluxe Hill View Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=1,
            ),
            ItineraryHotelNested(
                name='The Woods Resorts / After the Rains / Similar',
                location='Vythiri / Kalpetta (2N)',
                nights_label='02 Nights',
                description='Premium cottage block amid mist-clad valleys.',
                stars=4,
                category_label='Premium',
                room_type='Premium Cottage',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=2,
            ),
            ItineraryHotelNested(
                name='Mountain Shadows Resort / Pepper Trail / Similar',
                location='Vythiri / Kalpetta (2N)',
                nights_label='02 Nights',
                description='Luxury lake-view villa with adventure concierge.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Lake View Villa',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=3,
            ),
            ItineraryHotelNested(
                name='Evolve Back Kabini / Vythiri Resort Treehouse / Similar',
                location='Vythiri / Kalpetta (2N)',
                nights_label='02 Nights',
                description='Ultra-luxury treehouse or private pool villa.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Private Pool Villa / Luxury Treehouse',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=4,
            ),
            ItineraryHotelNested(
                name='Wayanad Silver Woods / Similar',
                location='Sulthan Bathery (2N)',
                nights_label='02 Nights',
                description='Deluxe boutique resort near adventure circuit.',
                stars=4,
                category_label='Deluxe',
                room_type='Deluxe Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=5,
            ),
            ItineraryHotelNested(
                name='Vythiri Meadows / Similar',
                location='Sulthan Bathery (2N)',
                nights_label='02 Nights',
                description='Premium boutique resort with forest views.',
                stars=4,
                category_label='Premium',
                room_type='Premium Room',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=6,
            ),
            ItineraryHotelNested(
                name='Banasura Hill Resort / Similar',
                location='Sulthan Bathery (2N)',
                nights_label='02 Nights',
                description='Luxury earth-resort near Banasura Sagar Dam.',
                stars=5,
                category_label='Luxury',
                room_type='Luxury Cottage',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=7,
            ),
            ItineraryHotelNested(
                name='Vythiri Resort Premium Deck / Similar',
                location='Sulthan Bathery (2N)',
                nights_label='02 Nights',
                description='Ultra-luxury deck suite with rainforest panoramas.',
                stars=5,
                category_label='Ultra Luxury',
                room_type='Ultra Premium Deck Suite',
                meal_plan="MAPAI (Breakfast & Dinner)",
                sort_order=8,
            )
        ],
        inclusions=_standard_inclusions(extra_included=["04 nights premium eco-resort accommodation across Vythiri/Kalpetta and Sulthan Bathery", "Complimentary 4x4 jeep safari passes and Kuruva Island bamboo rafting entry vouchers"]),
    )
    return package, itinerary, KL_010_PEXELS_IMAGES
